Add approval field in edit entry and Save value after update
GravityKit/GravityView pull request #2077
Opened 2024-06-11 06:53 UTC by omarkasem

- Added approval field as radio buttons in the edit form
- Made the field id unique to be able to retrieve it later to update

2024-06-12 13:24 UTC, mrcasual requested changes
@omarkasem, the PR works, thanks! Please address the comments and keep them in mind for your future contributions.

2024-06-12 13:24 UTC, mrcasual commented on includes/fields/class-gravityview-field-approval.php
> +				if ( isset( $_POST[ 'input_' . $unique_id ] ) ) {
@omarkasem, this statement can be expressed as `$value = $_POST[ "input_{$unique_id}" ] ?? $value`. Please try to use this style going forward.

2024-06-13 02:02 UTC, omarkasem commented on includes/fields/class-gravityview-field-approval.php
> +				if ( ! \GV\Utils::get( $edit_field, 'show_label' ) ) {
@mrcasual Yes i first did the $edit_field part but I saw that Utils were used all over the plugin files so I used it to be consistent

2024-06-13 02:06 UTC, omarkasem commented on includes/fields/class-gravityview-field-approval.php
> +		$unique_id = crc32( 'is_approved' );
@mrcasual Yes i thought about doing that but the input field id is converted to integer in the gravity forms so it always has to be input_%d, So this is the best hashing i found that worked perfectly as it generates a big number and it would be very very hard to have that number of inputs in the page as gravity forms does it from 1,2,3,4 etc..

2024-06-13 02:10 UTC, omarkasem commented on includes/fields/class-gravityview-field-approval.php
> +				if ( ! \GV\Utils::get( $edit_field, 'show_label' ) ) {
@mrcasual Is there a way to know which classes are legacy so i would avoid using them? I looked at Utils class but can't find any comments about legacy or deprecated

2024-06-13 04:07 UTC, omarkasem commented on includes/fields/class-gravityview-field-approval.php
> +			} else {
@mrcasual Did you test it without the else statement? because that will remove any other fields in the edit page even if we add continue

2024-07-02 17:36 UTC, mrcasual commented on includes/fields/class-gravityview-field-approval.php
> +			} else {
@omarkasem, here's the existing code simplified:

```php
foreach ( (array) $edit_fields as $id => $edit_field ) {
	if ( 'entry_approval' === $edit_field['id'] ) {
		// logic
	} else {
		// logic
	}
}
```

I proposed to `continue` in the first conditional statement. This way you don't need the `else` statement since nothing else happens after it. This just improves readability.

2024-07-02 17:40 UTC, mrcasual commented on includes/fields/class-gravityview-field-approval.php
> +				if ( ! \GV\Utils::get( $edit_field, 'show_label' ) ) {
> @mrcasual Is there a way to know which classes are legacy so i would avoid using them? I looked at Utils class but can't find any comments about legacy or deprecated

@omarkasem, basically, those helper classes exist due to us previously supporting PHP 5.x. There is no longer a need to use them since `$edit_field['show_label'] ?? false` is the same as `\GV\Utils::get( $edit_field, 'show_label')`. So while they are not marked as "legacy", we should strive to use PHP 7.2+ syntax wherever possible.

2024-07-02 17:42 UTC, mrcasual commented
@omarkasem, please review all comments and let me know when everything's done so that I could test the PR. Merci!

2024-07-12 04:21 UTC, omarkasem commented
@mrcasual All notes are done, Please check now

2024-07-30 20:05 UTC, rafaehlers commented
This works great! 🙌 https://www.loom.com/share/1fd52fd9fb8a48bb9fb7e79cedfa4185

2024-08-05 15:22 UTC, zackkatz commented
@mrcasual Please merge

2024-08-05 15:40 UTC, merged