Add fied time and date merge tags modifier
GravityKit/GravityView pull request #2080
Opened 2024-06-14 04:32 UTC by omarkasem

- I created merge tags modifier 'format' for both time and date
- The only thing that is not clear to me is when does this hook run
gravityview/merge_tags/modifiers/value
I tried a lot of values and modifiers but I can't get it to run so i can see if it has anything to do with date or time

2024-07-02 17:00 UTC, mrcasual requested changes
@omarkasem, in addition to my comments, could you also please add some unit tests?

2024-07-02 17:00 UTC, mrcasual commented on includes/class-gravityview-merge-tags.php
> +			return apply_filters( 'gravityview/merge_tags/no_modifiers/value', $value, $modifier, $field );
@omarkasem, we use the `gk/plugin/foo/bar/baz-bax` format for all new filters that we add (`gk/gravityview/merge-tags/no-modifiers/value` in your case). Also, why did you choose to use `no-modifiers/value` when the docblock reads "Modify the merge tag modifier output"? Would it make sense to use `modifiers/value`?

2024-07-02 17:00 UTC, mrcasual commented on includes/fields/class-gravityview-field-date.php
> +		add_filter( 'gravityview/merge_tags/no_modifiers/value', array( $this, 'replace_merge_tags_format' ), 10, 3 );
@omarkasem, I think it would make sense to fix `gravityview/merge_tags/modifiers/value` rather than adding a new filter.

You mentioned that "The only thing that is not clear to me is when does this hook run gravityview/merge_tags/modifiers/value". Looking at the [underlying code](https://github.com/GravityKit/GravityView/blob/f825710332284fd843bff339ba5c7606d28064ce/includes/class-gravityview-merge-tags.php#L54-L103), that hook doesn't run because `format` is not one of the GV modifiers. The [commit that added it](https://github.com/GravityKit/GravityView/commit/3dee20fdb466d25d3a9189096ef0c09b4fcf2ea3) appears to be incomplete. I suggest adding a `format` modifier and updating both the Date and Time fields to take advantage of it, rather than duplicating the functionality via the `gravityview/merge_tags/no_modifiers/value` hook and the associated methods (e.g., `replace_merge_tags_format`).

2024-07-12 03:47 UTC, omarkasem commented on includes/fields/class-gravityview-field-date.php
> +		add_filter( 'gravityview/merge_tags/no_modifiers/value', array( $this, 'replace_merge_tags_format' ), 10, 3 );
@mrcasual Yes you are correct, I just did a commit that fixed that

2024-07-12 08:03 UTC, omarkasem commented
@mrcasual 
So the tests are working fine because I'm calling `process_modifiers` directly but the main issue here is with the view in custom content with any date or time formats that has uppercase like D for days or F for months, gravityforms do strtolower to the modifier before it reaches to our function so there's no way to know what it was before or prevent that (see screenshot)

![Screenshot from 2024-07-12 11-00-30](https://github.com/user-attachments/assets/91cd27f1-79dd-4a4f-a0b2-771a76ef3066)

Do you have any idea how to bypass that? or should i try process the date and time away from that function like i was doing before.

2024-08-07 18:53 UTC, mrcasual commented
@omarkasem, please see my solution: https://github.com/GravityKit/GravityView/pull/2080/commits/2930ecfc2d0a86e97a5fc7ecba47a75728802b76.

2024-08-07 18:53 UTC, mrcasual approved these changes

2024-08-07 18:58 UTC, merged

2024-08-07 21:09 UTC, omarkasem commented
@mrcasual 
Yeah that's very smart to store it in a variable then call it back, well done :+1: :tophat: