Update settings on template activation
GravityKit/GravityView pull request #2144
Opened 2024-09-17 11:40 UTC by doekenorg

This PR addresses #2117 

After activating or installing a plugin, the selectors are updated; and the settings block is re-rendered and replaced. This will ensure all the new settings are available.

💾 [Build file](https://www.dropbox.com/scl/fi/r845y7ujndgz7pjuztop9/gravityview-2.29-12afca1a4.zip?rlkey=iy270yx0yabawfamj6za0esvr&dl=1) (12afca1a4).

2024-09-25 13:53 UTC, mrcasual commented
@doekenorg, is this PR ready for review/testing? If so, please update the Project information, `@` tag folks, etc.

2024-09-25 14:01 UTC, doekenorg commented
I updated the connected issue, but I have now updated this one as well. I'm not sure which I should update now. Doing both sounds too much.

2024-09-25 18:19 UTC, zackkatz requested changes
Looks good code-wise @doekenorg 👍 Just a couple commented-out lines.

2024-09-25 18:19 UTC, zackkatz commented on assets/js/admin-views.js
> +				// .on( 'tabscreate', viewGeneralSettings.tabsCreate )
Remove unused code

2024-09-25 18:19 UTC, zackkatz commented on assets/js/admin-views.js
> +				// .off( 'tabscreate', viewGeneralSettings.tabsCreate )
Remove unused code

2024-09-25 18:24 UTC, doekenorg commented on assets/js/admin-views.js
> +				// .off( 'tabscreate', viewGeneralSettings.tabsCreate )
Wasn't sure if I could remove this, but it looks like I can.

2024-09-26 14:32 UTC, mrcasual commented
@Mwalek, please test.

2024-09-26 19:56 UTC, Mwalek commented
@doekenorg @mrcasual looks good! I tested with PHP versions 7.4 & 8.3.

While testing this I found a few minor issues that are indirectly related to this functionality. @mrcasual before I create GH issues for them, could you please have a look and see if they're all things we want to fix?

Loom Video: https://www.loom.com/share/0665547e6d8b4a7dbb500ef8fb0bb618

- In the default template selection layout, aside from the outline on the button, there is no indication that the plugin is installing.
- Clicking "Install and Activate" or "Activate" from the placeholder behaves differently than performing the same action from the dropdown. The page is reloaded and data is lost.
- Placeholders in the settings menu show the "Upgrade" option when hovered, even though the All Access license is active. It should display "Install/Activate" instead.
- When using the placeholder to activate, the user is prompted twice for confirmation about leaving the page: once via the page itself and once through a browser modal.

2024-09-26 20:41 UTC, mrcasual commented
@Mwalek, the status indicator, upgrade badge, and confirmation messages are minor issues that should be corrected. What's more concerning is that when you click to install and use DataTables, the View type dropdown still shows Table.

In the order of priority:

1) When creating the View and selecting the View type, the View type of the Multiple Entries layout should be the same.
2) Loading indicator should be displayed when installing the layout in the View type selection during View creation
3) Upgrade badge + confirmation message (these can also be resolved under a separate PR)

@doekenorg, over to you.

2024-10-01 10:39 UTC, doekenorg commented
I've created https://github.com/GravityKit/GravityView/issues/2158 to address the other issues.

2024-10-01 10:40 UTC, doekenorg commented
@Mwalek Back to you for (hopefully final) testing.

2024-10-01 20:23 UTC, Mwalek commented
@doekenorg thank you! I retested this and can confirm that the following issues are resolved by the latest build:

>1) When creating the View and selecting the View type, the View type of the Multiple Entries layout should be the same.
>2) Loading indicator should be displayed when installing the layout in the View type selection during View creation

2024-10-01 21:52 UTC, merged