Fix embedded views in other fields
GravityKit/GravityView pull request #2149
Opened 2024-09-23 18:36 UTC by omarkasem

- Fixes https://github.com/GravityKit/GravityView/issues/2090
- The wpautop function breaks the scripts from Datatables, So I disabled them for all gv views fields in this area

2024-09-23 19:28 UTC, zackkatz requested changes

2024-09-23 19:28 UTC, zackkatz commented on includes/class-api.php
> +	if ( '' !== $placeholders['value'] && ! empty( $args['wpautop'] ) && (isset($field['id']) && $field['id'] !== 'gravityview_view') ) {
Thanks for this, @omarkasem.

Please:

1. Fix spacing
2. Assign to a variable outside the logic check
3. Use `\GV\Utils::get( $field, 'id' )` intead of checking isset

2024-09-24 04:51 UTC, omarkasem commented on includes/class-api.php
> +	if ( '' !== $placeholders['value'] && ! empty( $args['wpautop'] ) && (isset($field['id']) && $field['id'] !== 'gravityview_view') ) {
@zackkatz 
All done 
But I think @mrcasual Told me before that we want to phase out the use of the legacy Utils helper class, So should i try to use it more or not?

2024-09-24 12:14 UTC, mrcasual commented on includes/class-api.php
> +	if ( '' !== $placeholders['value'] && ! empty( $args['wpautop'] ) && (isset($field['id']) && $field['id'] !== 'gravityview_view') ) {
@omarkasem, correct, I asked not to rely less on helpers and instead use native PHP. 

`(isset($field['id']) && $field['id'] !== 'gravityview_view'` 

can be expressed as 

`'gravityview_view' !== ( $field['id'] ?? '' )`.

2024-09-24 13:24 UTC, mrcasual commented
@Mwalek, please test.

2024-09-24 15:03 UTC, Mwalek commented
@mrcasual this is working as expected.

E.g: https://basecamp.try.gravitykit.com/view/issue-2090-view/entry/26/

2024-09-24 21:09 UTC, merged