Fixes reversing issue
GravityKit/GravityView pull request #2157
Opened 2024-09-30 18:46 UTC by omarkasem

- Fixes https://github.com/GravityKit/GravityView/issues/2125
- The issue was only happening if a gravity forms field is put before gravity view field
- And that was happening because of a logic inside the survey plugin that was reversing the field choices for some reason
![image](https://github.com/user-attachments/assets/b51dc843-846e-4303-8971-96085e0a8095)

2024-09-30 18:47 UTC, zackkatz commented on templates/fields/field-survey-html.php
> +		if( !empty($choices) && $choices[0]['text'] === 'Excellent' ){
@omarkasem Thanks for the fix. Please fix spacing.

2024-10-01 16:00 UTC, mrcasual requested changes

2024-10-01 16:00 UTC, mrcasual commented on templates/fields/field-survey-html.php
> +		if ( ! empty( $choices ) && $choices[0]['text'] === 'Excellent' ) {
@omarkasem, there a couple of issues here:

1) We use Yoda conditions
2) If someone's changed the choice text from `Excellent` to something else, your solution would fail

Please address these.

2024-10-02 18:26 UTC, omarkasem commented on templates/fields/field-survey-html.php
> +		if ( ! empty( $choices ) && $choices[0]['text'] === 'Excellent' ) {
@mrcasual Yes you are correct I didn't notice that they can change the choices, It's fixed now with the latest commit

2024-10-02 19:12 UTC, mrcasual commented on includes/fields/class-gravityview-field-survey.php
> +	 * Get field choices directly from the database (To avoid issues where choices are reversed by the survey plugin).
@omarkasem, `Gets field choices...`

2024-10-02 19:14 UTC, mrcasual commented on includes/fields/class-gravityview-field-survey.php
> +	 * @param int $field_id The ID of the field.
@omarkasem, please align param descriptions:

```
* @param int $form_id  The ID of the form.
* @param int $field_id The ID of the field.
```

2024-10-02 19:14 UTC, mrcasual commented on includes/fields/class-gravityview-field-survey.php
> +		$form_meta = GFFormsModel::unserialize( rgar( $form_row, 'display_meta' ) );
@omarkasem, please align variable assignments.

2024-10-02 19:15 UTC, mrcasual commented on includes/fields/class-gravityview-field-survey.php
> +		if ( $form_meta ) {
@omarkasem, please return early.

2024-10-09 14:49 UTC, omarkasem commented
@mrcasual Thanks for the notes, All done

2024-10-14 16:54 UTC, merged