Filter join conditions #2198
GravityKit/GravityView pull request #2206
Opened 2024-11-13 17:49 UTC by zahardev

Adds a filter for join conditions. Most immediately, this is required for https://github.com/GravityKit/Multiple-Forms/pull/105.

💾 [Build file](https://www.dropbox.com/scl/fi/rgwjagesqw34naf4rkgw6/gravityview-2.31.1-753893103.zip?rlkey=qphdqt1tkm7nd0pmiev3xx8bs&dl=1) (753893103).

2024-11-13 17:58 UTC, zackkatz requested changes

2024-11-13 17:58 UTC, zackkatz commented on future/includes/class-gv-view.php
> +					$status_conditions = apply_filters( 'gk/gravityview/view/entries/join_conditions', $status_conditions, $join, $this );
@zahardev Please add full docblocks for filters. See line 1137 and 1556 for an example.

2024-11-13 18:08 UTC, zahardev commented on future/includes/class-gv-view.php
> +					$status_conditions = apply_filters( 'gk/gravityview/view/entries/join_conditions', $status_conditions, $join, $this );
@zackkatz Could you please suggest the filter name here? Which is better - `gk/gravityview/view/entries-join-conditions`, gk/gravityview/view/entries/join-conditions` or something else?

2024-11-13 23:14 UTC, mrcasual commented
@zahardev, thanks for the fixes. Please fix the merge conflict and then hit that "merge" button.

2024-11-14 20:53 UTC, rafaehlers commented
FIY this has been tested: https://github.com/GravityKit/Multiple-Forms/pull/105#issuecomment-2477383089

2024-11-18 22:35 UTC, zahardev commented
@mrcasual 

Yes, we need that part for the strict Strict Entry Match view.

2024-11-19 16:58 UTC, merged