Adds heartbeat ajax functions from gf, Fixes enqueue issue and Fixes …
GravityKit/GravityView pull request #2242
Opened 2024-12-19 17:24 UTC by omarkasem

- Implements https://github.com/GravityKit/GravityView/issues/950
- Adds heartbeat ajax functions from gf `GFLocking` class
- Fixes enqueue issue that had a condition of joined forms in one view which i don't think can happen anymore(Loading multiple forms in one view)
- Fixes Modal issue in frontend where gf locking script depends on `#wpwrap` which exists in dashboard
- Fixes big issue in `check_user_cap_edit_entry` where it's called using heartbeat ajax functions and the issue is we can't pass $view_id to make sure the `user_edit` option exist as it happens in gf locking script, So i fixed it in a way that won't affect any other requests other than ajax requests

2024-12-19 22:56 UTC, mrcasual commented
@Mwalek, please test.

2024-12-20 12:54 UTC, Mwalek commented
@mrcasual @omarkasem I noticed the following:

1. Edit locking does not work when editing in a lightbox.
2. When control is requested by a user with the subscriber role, the user is shown their own gravatar and not the gravatar of the user that's currently editing.
3. Potential Enhancement: When control is requested, upon the person editing accepting the request, the user that requested access must click the "take control" button. This takes the user to the entry URL, instead of the edit entry URL.

## Summary
- [ ] Edit locking in lightbox
- [ ] Wrong gravatar shown
- [ ] Enhancement to go directly to edit URL

2024-12-29 18:07 UTC, omarkasem commented
@Mwalek Both issues are solved.
About the lightbox part,  I tried it but it will very hard to do as the whole gravity forms locking depends on getting the entry id being inside the edit entry  page and we will also have to load the whole locking js scripts inside the entries view list, Let me know if it's really important and i can spend some time on it

2025-01-02 11:31 UTC, Mwalek commented
@omarkasem thank you! I confirmed that the 2 issues are solved. The lightbox issue should not necessarily be fixed. I didn't face any other issues during tests 👌 

cc. @mrcasual

2025-01-02 14:19 UTC, mrcasual requested changes

2025-01-02 14:19 UTC, mrcasual commented on includes/extensions/edit-entry/class-edit-entry-locking.php
> +	protected function get_lock_request_meta( $object_id ) {
@omarkasem, please document all new functions.

2025-01-02 14:19 UTC, mrcasual commented on includes/extensions/edit-entry/class-edit-entry-locking.php
> +
@omarkasem, please do not add line breaks. We keep repeating asking this in almost every PR.

2025-01-02 14:19 UTC, mrcasual commented on includes/extensions/edit-entry/class-edit-entry-locking.php
> +		if ( array_key_exists( $heartbeat_key, $data ) ) {
@omarkasem, please exit early.

2025-01-02 14:19 UTC, mrcasual commented on includes/extensions/edit-entry/class-edit-entry-locking.php
> +		if ( array_key_exists( $heartbeat_key, $data ) ) {
@omarkasem, please exit early.

2025-01-02 14:19 UTC, mrcasual commented on includes/extensions/edit-entry/class-edit-entry-locking.php
> +				if ( $new_lock = $this->set_lock( $object_id ) ) {
@omarkasem, `@new_lock` is not used.

2025-01-02 14:19 UTC, mrcasual commented on includes/extensions/edit-entry/class-edit-entry-locking.php
> +			if ( ( $user_id = $this->check_lock( $object_id ) ) && ( $user = get_userdata( $user_id ) ) ) {
@omarkasem, please avoid using inline assignments as they make code harder to read.

2025-01-10 21:38 UTC, omarkasem commented on includes/extensions/edit-entry/class-edit-entry-locking.php
> +
@mrcasual Thanks for the reminder but I copied the functions from the gf-locking class like the rest of the file was, I was just trying to stay consistent with the styling in the same file

2025-01-10 21:40 UTC, omarkasem commented on includes/extensions/edit-entry/class-edit-entry-locking.php
> +		if ( array_key_exists( $heartbeat_key, $data ) ) {
@mrcasual 90% of our class is copied from the gf-locking class as we depend on it's functions in everything in this locking feature, Should we change their functions or keep it as it is?

2025-01-10 21:41 UTC, omarkasem commented on includes/extensions/edit-entry/class-edit-entry-locking.php
> +			if ( ( $user_id = $this->check_lock( $object_id ) ) && ( $user = get_userdata( $user_id ) ) ) {
@mrcasual Thanks for the note and I totally agree with the point, It's just copied as mentioned before and I tried to not change anything so we stay consistent with the gf locking class

2025-01-13 03:16 UTC, mrcasual commented on includes/extensions/edit-entry/class-edit-entry-locking.php
> +		if ( array_key_exists( $heartbeat_key, $data ) ) {
@omarkasem, that's fine, thanks for the context. Perhaps adding a `@since` and `@see` tags would help explain things for someone who doesn't such context.

2025-01-13 20:28 UTC, rafaehlers commented
> * [ ]  Edit locking in lightbox
> *

@mrcasual the only thing missing in this PR is supporting the edit lock functionality inside a lightbox. Can you help Omar with the steps necessary?

2025-01-13 20:28 UTC, rafaehlers commented
> @Mwalek Both issues are solved. About the lightbox part, I tried it but it will very hard to do as the whole gravity forms locking depends on getting the entry id being inside the edit entry page and we will also have to load the whole locking js scripts inside the entries view list, Let me know if it's really important and i can spend some time on it

@mrcasual the only thing missing in this PR is supporting the edit lock functionality inside a lightbox. Can you help Omar with the steps necessary?

2025-01-27 22:50 UTC, mrcasual commented
@Mwalek, please test entry locking in a lightbox.

2025-01-28 13:10 UTC, Mwalek commented
@mrcasual looks good! No issues encountered while testing entry locking in the lightbox.

2025-01-28 13:21 UTC, merged